# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on: [push, pull_request]

# The jobs that will be run, usually in parallel
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: yarn install
    - uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
      with:
        coverageCommand: yarn coverage
        coverageLocations: |
          ${{github.workspace}}/coverage/cypress-coverage/clover.xml:clover
        debug: true