# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on: [push, pull_request]

# The jobs that will be run, usually in parallel
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: yarn install
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: yarn global add nyc
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - run: yarn test
      - run: ./cc-test-reporter format-coverage
      - run: ./cc-test-reporter sum-coverage
      - run: ./cc-test-reporter upload-coverage
      - uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          coverageCommand: yarn report:combined
          debug: true